### ISSUE TITLE
Correctly inactivate action for inactive player

### ISSUE THREAD

**Issue by bibirico** [seagiants/crystal-hunt#2]
When its other player's turn, one can still interact with some elements (clicking on ActionTile will select a a skill for example).
All interactions during opponent's turn should be impossible.

**Comment by romaintailhurat** [comment]
A simple isActive props on top level components should do the trick: https://github.com/seagiants/crystal-hunt/blob/cb9526fc5de98af8a0a00e2be16eadb29cd7788d/src/components/GameBoard.tsx#L31

**Comment by bibirico** [comment]
Yep. To do.

**Comment by romaintailhurat** [comment]
Oh, excellent, will use that!

**Comment by romaintailhurat** [comment]
Implemented in https://github.com/seagiants/crystal-hunt/commit/4d3245821361e3720f323c78f5e3f960bd76874c
