### ISSUE TITLE
Refactor librairies

### ISSUE THREAD

**Issue by bibirico** [seagiants/crystal-hunt#6]
A correct librairies mechanism is needed.
Using plain js object to store function is okish, but hard to add new ones and can't easily link ones to others, ie: A power function can't easily call another power function as they're defined as properties of the same object.

**Comment by romaintailhurat** [comment]
Use the module concept instead of an object, ie each power is a standalone object or class living in the same module (file).

In powerLib.js, something along the lines of:

```javascript
interface Power {
  power: (g: SimpleGame, ctx: GameContext) => modifiedGame: SimpleGame;
  check: (g: SimpleGame, ctx: GameContext, targetId: string, caracs: Caracs) => ok: boolean;
}

export const Move: Power = {
  power: <actual implementation>,
  check: <actual implementation>
} 

export const Attack: Power = {
  power: (...) => Move.power(...)
}
```

**Comment by bibirico** [comment]
Then you retrieve a power by a simple ?

```javascript
import * as POWER from powerLib.js;

const getPower : Power = (powerName: string) => return(POWER[powerName]);
```
